### ISSUE TITLE
Could not find org.springframework.security:spring-security-webflux

### ISSUE THREAD

**Issue by akoranne** [mohitsinha/tutorials#1]
I am able to compile the repo as is without issues. 
However, when I changed `springBootVersion` to '2.0.0.M7', I get the above error. 
It works with '2.0.0.M5' but not M7.  And that is what Spring Initializer has in its options.

Do you know where the spring security webflux package has moved to, in M7 (from M2)?

**Comment by mohitsinha** [comment]
I am not aware of any major changes, but I suggest that you to take a look at the release notes for each milestone release. 
If you still aren't clear what is causing the code to break, you can raise an issue in the official Spring Boot project in Github.

Hope this helps.

**Comment by mohitsinha** [comment]
This has been moved to spring-security-web. 
You can explore more about this issue here.
https://github.com/spring-projects/spring-security/issues/4662

Hope this helps.
